

# MINI PROJECTS - 02 : -

# Project Name : Random Password Generator(For User As per user length)

# Discription : We need to generate as per user length(may 12 char or less) password combination of UpperCase, LowerCase and Special Symbols/Punctuators for Strong Passoword. Ex: Whenever we are signing up on any site, Google Chrome Suggest us a strong password to put(that is generated by Google Chrome when we are registering password for very first time)

# Combining all Possible Characters(UpperCase, LowerCase, Digits, Punctuators) for generating Password -

import string
import random

all_chars = string.ascii_letters + string.digits + string.punctuation  #Reuturns all ASCII character including UpperCase, LowerCase, Digits, Punctuators.

# print( random.choice(all_chars) ) # Generates a unique random character from sepcified iterable object.


pw_length = 12
password = ""

# Want to retun 12 Character from iterable object, using for loop -
for i in range(pw_length):
    password += random.choice(all_chars) 

print(f"Your Random Password({pw_length}-Char) Is : {password}")    





# Let's Bind IT In A  FUNCTion with user-defined password_length to generate -

import string
import random

def generatePassword(pw_length):

    all_ASCII_chars = string.ascii_letters + string.digits + string.punctuation

    my_Password = ""
    for i in range(pw_length):
        my_Password += random.choice(all_ASCII_chars)

    #Finally We will return our generated password -
    return f"Your Generated Password Is : {my_Password}"

print(generatePassword(12))  # Mention the pAssword length HEre.